### ISSUE TITLE
Charts do not get generated after running simulation

### ISSUE THREAD

**Issue by maurofughi** [pyscripter/XLRisk#10]
Hello,
first of all thank you for this amazing tool, which I am starting using for running MC simulations for trading strategies.
I have done quite a few simulations with a few hundreds simulations and it works fine. Now that I am close to my final results I am running larger simulation, with 10000 runs, and I noticed Charts do not get created?
I wonder whether there is a limit of runs for the charts or something else? Another difference with previous simulations that worked OK is the sample size (number of variables that I simulate with uniform distribution) as so far I have used samples with size of 100 or 120, this one has size 360 (simulated 10000 times), again not sure there is a limit? Statistics are calculated OK, but no charts are generated.

Just to add another point in regards of Tornado Graph, I wonder if it should pick description of the Y axis values from the column before the source one as it does in the NOVA example, but in my case it always shows just the cell reference number (see second picture attached from another smaller simulation I did).

I am using Excel 365 latest version.
Thanks!

![image](https://github.com/pyscripter/XLRisk/assets/148484993/09f61a4d-6d0a-4aea-82a0-13549c44324c)
![image](https://github.com/pyscripter/XLRisk/assets/148484993/c2305efe-8651-48ff-ba91-948a0c202c8a)

**Comment by pyscripter** [comment]
There are no fixed limits to either the number of simulation iterations or the number of the variables.

> Just to add another point in regards of Tornado Graph, I wonder if it should pick description of the Y axis values from the column before the source one as it does in the NOVA example, but in my case it always shows just the cell reference number (see second picture attached from another smaller simulation I did).

The tornado diagram uses range names instead of cell references if they are defined.   That is why you see labels in Nova tornado results.

In the chart above all correlations are less than 0.2.   You can get a better picture if you change the min/max X-axis values.

I am not sure why the graphs are not generated.    It would help if you attach here an example file demonstrating the issue.

**Comment by maurofughi** [comment]
OK thanks for the quick reply, please see attached an example of one of those that do not create charts.

Also, from what you say about descriptions on Tornado Charts, does that mean there is a way to make it picking up my descriptions -- i.e. should I create some cell ranges with certain names (could not find this info)?
And yes I know I can adjust axis for that, just focussing on the issues for now.
Thanks!
[PH PORT R-SIMv2.zip](https://github.com/pyscripter/XLRisk/files/13050465/PH.PORT.R-SIMv2.zip)

**Comment by pyscripter** [comment]
> does that mean there is a way to make it picking up my descriptions -- i.e. should I create some cell ranges with certain names (could not find this info)?

In [SimResults](https://github.com/pyscripter/XLRisk/wiki/SimResults):

> Input cells are the cells containing risk distribution functions. The first columns of the results sheet under the heading "Inputs" contain the sampled values of the input cell for each iteration. The cell address or name, if the cells containing input distributions are named, as is the case here, and the formula of each input cell are displayed at the top of each column.

**Comment by maurofughi** [comment]
OK, I normally do not use "names" as I prefer ranges but understood, and I tried and it works now to have names to show in the Tornado Graph.

If you can also help in those that do not create charts would be great!

One question that I had is also whether it is possible to have in the same excel file multiple simulations, one per tab?
That was my intention but I tried and it does not seem to work, meaning it seems I can only have 1 simulation in each excel file. I tried creating a second one but it would override the existing one, probably because the simulation setting tab called XLRisk can only be defined once for each excel file?

Thanks!

**Comment by pyscripter** [comment]
You can have multiple results but just one XLRisk sheet.

What you can do is you can define a simulation, then rename the sheet say XLRisk1 and then define a second.   If you want to go back to the original you rename the sheets.

**Comment by maurofughi** [comment]
OK yes I can do that so to keep multiple simulations in one excel file.

But I continue to have more and more simulations that do not generate charts at all. Now with any number of simulations, not only with high number as I tried even with 100 and still no charts.
I wonder if rather than the number of simulations maybe there is a limit in the number of samples included in the distribution from which to generate random numbers?
In my earlier simulation I was dealing with samples of about 120 numbers (always using uniform distribution). Now I have samples with 360 and also 1000 numbers, these do not generate charts.
Any help appreciated as I invested a lot of time in this tool as it was working so well, now unfortunately doesn't generate charts anymore.
Thanks!

**Comment by maurofughi** [comment]
I did some further testing, trial and error really, and it seems the combination of number of values in the sample as well as number of simulations.
Tried one simulation with a sample of 120 and up to 10000 simulations, all fine.
Tried one simulation with a sample of 850 and 100 simulations, all fine.
Tried the same simulation with sample of 850 and 1000 simulations: NO charts.
There may be intermediate combinations but can't waste any more time on this as I need to progress my project.
I wonder if it is indeed some limit in the number of values that go on the chart (would not understand why as I am sure excel does not have such a low number for data series), but in any case if you can check and in that case just limit the values that go on the charts, still better that having no charts at all.
I am particularly interested in the histograms and cum distribution which should have no limitations as they do not plot all values or simulations. The more suspicious one is the Tornado Chart that is actually the one that with my work is the most irrelevant as I have individual samples values so in that case an option to just exclude that chart and leaving the important ones (histograms and cum distribution). Just some ideas as without coding skills not much else I can do.
Thanks.

**Comment by pyscripter** [comment]
Please download again and test.

**Comment by maurofughi** [comment]
You mean download the XL Risk and reinstall it?
Is that because you make some changes?

I have done a lot of work already so need to know why I would need to re-do all over it again.
Thanks.

**Comment by pyscripter** [comment]
> Is that because you make some changes?

Yes

**Comment by maurofughi** [comment]
OK, I tried with the latest file and it works, I can see it also generates a much bigger Tornado diagram, probably to show all the values I have, so it's good.
I will try also with the other simulations that did not create charts and will let you know if I find any other issues, but so far seems good.
Many Thanks!
