### ISSUE TITLE
Run time error '91':  Object Variable or With block variable not set

### ISSUE THREAD

**Issue by vinunderwood** [pyscripter/XLRisk#14]
I installed XLRisk per the instructions at "Download and Install."  I opened the spreadsheet I want to use XLRisk on and when I clicked on XLRisk / Setup I got the error message above.  I clicked on Debug and it pointed me to the line of code in the attachment.

I am on a Windows laptop (Dell G5 SE), Windows 10 Home, Microsoft Office Professional Plus 2016 with Excel and other office products.

Any advice?

Thanks,
Vin Underwood
![Bad Line of Code](https://github.com/pyscripter/XLRisk/assets/36025670/973db2f3-68f2-4c0e-b634-7f0018485d3b)

**Comment by pyscripter** [comment]
No idea!  Does it happen consistently? Say if you close and start again Excel?  Does it happen with an empty workbook?

**Comment by vinunderwood** [comment]
My next step is to either uninstall and re-install, or to rebuild my workbook from scratch, omitting a lot of fluff and hidden sheets.  I think the second option is more promising.

**Comment by pyscripter** [comment]
Can you post your workbook here (or a  link to it), so that I can have a look?

**Comment by vinunderwood** [comment]
sure - attached.

oops - wouldn't attach.  Got an error message "We don't support that file type".  Maybe the problem is that it is a xlsm file??

**Comment by pyscripter** [comment]
Put it in a zip file. Would that work?  Otherwise place in a sharable cloud storage (onedrive, google drive etc.) and post a link.

**Comment by vinunderwood** [comment]
I copied it to OneDrive.   It wouldn't let me copy the link and share.   I use 7-zip, which is not easily converted to zip format.  Let me download zip right now and I will create a zip file.

**Comment by vinunderwood** [comment]
before i create a zip file, I copied it to google drive.  Here is the link https://drive.google.com/file/d/1deSmgu0Luyt43cxLxejWdWnhDgjUMgYd/view?usp=sharing

**Comment by vinunderwood** [comment]
the file is Provenir Decision Engines - Queuing Perspective v3.0.xlsm.   I want to assign normal distributions or lognormal distributions to the blue cell on tab "Peak Hour", and the three blue cells on the tab "Final Calc".

**Comment by vinunderwood** [comment]
I want to disable this link as soon as you have looked at the file.  I don't want to share it with the whole world.

**Comment by pyscripter** [comment]
I have downloaded the file, so you can delete the link.

**Comment by pyscripter** [comment]
When I open your file VBA macros are disabled due to security issues.
I could reproduce the error.
Then I saved your file as an xlsx file (without the macros) opened it and XLRisk worked as expected.

**Comment by vinunderwood** [comment]
I did exactly as you suggested.  It solved the problem for me as well.  Thank you for debugging this for me!  Now I just have to figure out how your software works - I'm sure I won't have a problem - your doc looks pretty good and I worked with Crystal  Ball many years ago.

**Comment by pyscripter** [comment]
Good.

**Comment by vinunderwood** [comment]
correction to doc at https://github.com/pyscripter/XLRisk/wiki/RiskFunctions.  Your lognormal distribution formula is RiskLogNorm, not RiskLogNormal.

Also, what is the value meand in the function =RiskLogNorm(meand, stdev)?  Is it the mean or something else?  Maybe these parameters are the mean and standard deviation of my variable's natural logarithm?

 I coded =RiskLogNorm(1.5, 0.025) expecting to get a confidence interval approximately centered on 1.5, but I'm getting values like 4.34, 4.58. etc.

**Comment by pyscripter** [comment]
The correction to the docs was done.

This is the source fode for RiskLogNorm

```vba
Public Function RiskLogNorm(Mean As Double, StDev As Double, Optional Corrmat As Long = 0) As Double
'   Random sample from a Log Normal distribution
    
    Dim RndValue As Double
    Application.Volatile (ProduceRandomSample)
    
    If ProduceRandomSample Then
        If gSimulation Is Nothing Then
            RndValue = Rnd()
        Else
            RndValue = gSimulation.GetRndSample(Application.Caller)
        End If
        RiskLogNorm = WorksheetFunction.LogNorm_Inv(RndValue, Mean, StDev)
    Else
        RiskLogNorm = Exp(Mean + 0.5 * StDev ^ 2)
    End If
End Function
```
As you can see it uses the Excel function LogNorm_Inv.

From the [documentation](https://support.microsoft.com/en-us/office/lognorm-inv-function-fe79751a-f1f2-4af8-a0a1-e151b2d4f600) of LogNormInv you can see that Mean is the mean of Ln(x) and stdev the standard deviation of ln(x).

The mean of x is Exp(Mean + 0.5 * StDev ^ 2)

**Comment by vinunderwood** [comment]
yep - that was my guess.  thanks
