### ISSUE TITLE
Function OneRiskFunctionPerCell

### ISSUE THREAD

**Issue by SaraP00** [pyscripter/XLRisk#18]
Hello everybody, I have tried to implement XLRisk for a project and it's fastastic. The only downside is that I'm not allowed to use the IFS function that basically use a specific prob. function depending on the the type of distribution I choose. 
I know that its not a big of a deal writing directly the risk function in the cell but i need to make it as easier  and "automated" as possible.
I tried to add a new function in the macro library  with the help of chat gpt since i'm not used to write in VBA...this strategy was not a success i must say. 
Is there a way to avoid this issue?

**Comment by pyscripter** [comment]
XLRisk only allows one risk function per cell.   However, you can achieve the desired result, similar to IF and IFS, by using multiple cells, e.g.

A1: =RiskNormal(100, 20)
A2: =RiskTriang(80,100,120)
A3: =If(condition, A1, A2)

**Comment by SaraP00** [comment]
Thank you for the suggestion. I've tried to implement this but the error still pops up.

![rm](https://github.com/user-attachments/assets/493abeb8-8b5d-4d26-9583-3520e57f2f36)

**Comment by SaraP00** [comment]
thank you for the suggestion, I implemented it but the last limitation is that the function gives an errror when calculating, in this case the function RiskTriang but the inputs are just to use RiskUniform. 
![immagine](https://github.com/user-attachments/assets/ebf30860-21a7-49e7-9d20-21b84ad5c7e3)
The error comes from the function "Public Function SortedTable", specifically in the line ColVals(I) = Abs(Table.Cells(I, Col).Value)
because, as I imagine, it has to collect from the selected cell a value that is a positive number, not a text or a negative number.

Is there a way to modify this function?
Thank you again for your support.

**Comment by pyscripter** [comment]
Can you post your model here, so that I have a look?

**Comment by SaraP00** [comment]
[feedback_GitHub.xlsx](https://github.com/user-attachments/files/16727474/feedback_GitHub.xlsx)

**Comment by pyscripter** [comment]
There are no XLRisk functions in this worksheet.  And cell S1 has an error value.   No idea what you are trying to do.

![image](https://github.com/user-attachments/assets/f4559352-7ae7-4b2f-afd1-a86783ee5bc0)

Can you post instead a **minimal** excel model that demonstrates the issue you are facing?

**Comment by SaraP00** [comment]
I'm sorry the functions got removed when I created the copy. I managed to solve the problem. Thank you again for your time and help!
