### ISSUE TITLE
Run-time error

### ISSUE THREAD

**Issue by maurofughi** [pyscripter/XLRisk#19]
Just got a run time error 13
Please see pics.
It has been working fine so far, also on this excel file, not sure why it started providing this error?

After this error excel seems to be working and I can see the risk results but the mouse gets stuck so I have to close and reopen excel.
![xlrisk1](https://github.com/user-attachments/assets/07f975ec-90d4-4339-83d7-470460e98c02)
![xlrisk2](https://github.com/user-attachments/assets/a5719c89-d398-4705-a5de-47b3ea5e52be)

**Comment by pyscripter** [comment]
Could you please attach here the Excel file in which the error occurs?

**Comment by maurofughi** [comment]
OK, I had to strip down all non relevant and private info and data and I left only what is needed by the XLrisk to run. See attached.
[DC Portfolio Optimization2.xlsx](https://github.com/user-attachments/files/17164278/DC.Portfolio.Optimization2.xlsx)

**Comment by maurofughi** [comment]
Just checked again and still get that error also in this version so you should be able to see it.

**Comment by pyscripter** [comment]
- I have renamed the sheet XLRisk to XRisk2.
- I recreated the XLRisk sheet by invoking the XLRisk settings and pressing OK
- I then copied the outputs from XLRisk2 to XLRisk

I saved the file and opened it, run a simulation no issues.

Not sure what was wrong with the original XLRisk sheet.
Could you please confirm the above works?

**Comment by maurofughi** [comment]
Actually I just realized that in the file I sent you there was a missing link so the model would not calculate. If you run a simulation it must have been empty results as you should see the model not updating, which is probably why you had no errors. Please see the correct file, same as before but with the missing link. If you press F9 you will see the output changing, which you would not see before. This still shows the error if run it.
[DC Portfolio Optimization2.xlsx](https://github.com/user-attachments/files/17167131/DC.Portfolio.Optimization2.xlsx)

**Comment by maurofughi** [comment]
The other thing I noticed is after this error happens, it disables automatic formulae calculation in excel, any excel also those with no XL risk so need to switch it back on automatic otherwise formulae won't recalculate, so you know.

**Comment by pyscripter** [comment]
If you delete the sheet "Risk Results 1" and save the spreadsheet the error when opening the spreadsheet goes away.

Regarding you model it is unclear what you are trying to do.   The random functions are in range TOT!S12:S25 but they are not used anywhere, so the results of the  simulation are not affected and they stay constant.  For the simulation to make sense the results need to be linked to the uncertain variables.

**Comment by maurofughi** [comment]
You must have been using again the first file I had sent you, instead of the second file. As mentioned, the first file had the links removed. You have to look at the second file that has all the links. I will attach with a different name so you will not be confused. Please run XL risk on this one **DC Portfolio Optimization3**

If you are in the TOT tab and click Show Samples and press F9 you can easily see what the model does.

The error is not when opening the file, the error occurs at the end of the XLRisk run, so it is caused by XLRisk.
[DC Portfolio Optimization3.xlsx](https://github.com/user-attachments/files/17172229/DC.Portfolio.Optimization3.xlsx)

**Comment by pyscripter** [comment]
OK.  The problem is due to the fact that the distributions in cells TOT!W22 and TOT!W23 have a stdev of 0 (just one value).
If you replace the formulas in the above cells with their only value 1, then everything will work as expected.

**Comment by maurofughi** [comment]
Ah, perfect thanks. I actually thought of that when I switched to just one value as initially I had more than 1 and it worked, then I thought whether to just remove those two lines or keep them with 1 value. Makes sense. Thanks!

**Comment by maurofughi** [comment]
Just one question as I was trying to run simulations with more than my usual 10,000 runs, and I tried 50,000 but it seems I get an error "Invalid Number" every time I enter a number of iterations over 30,000
Is 30,000 the maximum iterations XLRisk allows?

**Comment by pyscripter** [comment]
The maximul allowed no of iterations currently is 327677.   This is not by design though and will soon be fixed.  See https://github.com/pyscripter/XLRisk/issues/20.

**Comment by maurofughi** [comment]
Great, Thanks!
