### ISSUE TITLE
Excel crash when generating the reports

### ISSUE THREAD

**Issue by APL78** [pyscripter/XLRisk#2]
First of all thanks for this excel Add-in. Very simple, very useful !
Here is the issue. when there is a lot of risk functions and a lot of iterations, Excel (MacOS version 16.34) crashes at the reports creation's step (ProduceCumulativeDistributions, ...), more precisely when creating the charts.

I had a look on Internet and found this: https://stackoverflow.com/questions/36232382/initializing-chart-object-in-crashes-vba .

So I inserted `R.Select` before each `Set NewChart = mOutSheet...` instruction and now it works fine for me. 

Cheers

**Comment by pyscripter** [comment]
> First of all thanks for this excel Add-in. Very simple, very useful !

Then please star the project.  It will give greater visibility!

**Comment by pyscripter** [comment]
Should be fixed with the last couple of commits.
Please test again.
