### ISSUE TITLE
Lognormal distribution abnoramilties

### ISSUE THREAD

**Issue by regala28** [pyscripter/XLRisk#23]
Hello I was simulating a simple lognormal distribution with mean of 100 and standard deviation of 10, but when I use the risklognormal distribution I get extremely huge values.

Then I triend using as input to the function mean of 2 and sdev of 1 as if I needed to apply logarithm to the values but still have huge values which, after doing the 1,000 iterations, do not have a mean nor sdev close to what I input.

Do you know what's the problem? 
With other software If I simulate lognormal(100,10) i get a mena to the iterations close to 100 and sdev close to 10.

<img width="219" alt="image" src="https://github.com/user-attachments/assets/506b7c0e-c5ab-43d8-bf74-ae19a46b97f1">
<img width="224" alt="Screen Shot 2024-11-21 at 17 46 00" src="https://github.com/user-attachments/assets/c3802f0c-f6ff-4c80-bb37-2a110bc5e944">

**Comment by pyscripter** [comment]
Please see https://github.com/pyscripter/XLRisk/issues/14#issuecomment-1977479723
