### ISSUE TITLE
Excel crashes when running some simulations

### ISSUE THREAD

**Issue by dwschaffner** [pyscripter/XLRisk#3]
Attached are copies of the crash report and the excel file.
[crash report.txt](https://github.com/pyscripter/XLRisk/files/7964040/crash.report.txt)
[Scenario 2 new.xlsx](https://github.com/pyscripter/XLRisk/files/7964045/Scenario.2.new.xlsx)
.

**Comment by pyscripter** [comment]
Which version of Excel are you using?

**Comment by dwschaffner** [comment]
Microsoft® Excel for Mac
Version 16.48 (21041102)
License: Microsoft 365 Subscription

**Comment by pyscripter** [comment]
Here it runs without problems.

**Comment by dwschaffner** [comment]
OK, I will let you know if I figure out what's causing it.

**Comment by pyscripter** [comment]
You can try running in a different machine to see whether it runs.

**Comment by pyscripter** [comment]
I am closing it since there is no feedback and the issue cannot be reproduced.
