### ISSUE TITLE
Incompatible with the version, platform, arch

### ISSUE THREAD

**Issue by linusdan97** [pyscripter/XLRisk#4]
Hii,

I was try this add-ins in Ms excel Prof Plus 2013 on Windows 10 Pro 64-bit.
When i am running the add-ins, it's shows a message box:
"Compile error in hiden module: Eigen.... and the cursor change to loading icon for long.
below the message screenshoot of the message:
![image](https://user-images.githubusercontent.com/103341504/162598944-6ce460fc-9573-4578-830e-6a763871ca8b.png)

I also try on macbook pro but it did succesfuly.

What i must do to run it on my windows laptop. thank you

Regards,

**Comment by pyscripter** [comment]
I have tested with Excel 2016 and later.   I do not have Excel 2013.  If you can find and fix the incompatibility please submit a PR or a list of changes that are required.

**Comment by linusdan97** [comment]
I am really new on this thing. Do you have any suggestion how/what step that i could start to fix it. What is a PR? Thank You

**Comment by linusdan97** [comment]
Hii, i have just fix the message error for the XLRisk add-ins.
First, I'm uncheck the XLRisk add-ins by File->Option->Add-ins->Manage->select->Go->uncheck->OK. 
Then install/check the Solver add-ins by File->Option->Add-ins->Manage->select->Go->check->OK.
After that check the XLRisk add-ins.
Thank you
