### ISSUE TITLE
Run-time error '13': Type mismatch

### ISSUE THREAD

**Issue by Ditya001** [pyscripter/XLRisk#5]
![Screenshot 2022-12-20 002919](https://user-images.githubusercontent.com/96434249/208473664-2a019d1e-f492-4059-9d57-c1fcbc91013b.png)
![Screenshot 2022-12-20 002851](https://user-images.githubusercontent.com/96434249/208473672-ac72fd03-6161-44f8-9794-44104f16dedf.png)

**Comment by pyscripter** [comment]
You are using an old version of Excel.  XLRisk needs Excel 2016 or later.
