### ISSUE TITLE
Tornado graph

### ISSUE THREAD

**Issue by Silex64** [pyscripter/XLRisk#6]
The tornado graph does not print out. It stays blank although the right output cell is referred to (sum of variables).

**Comment by pyscripter** [comment]
Which Excel version do you use.   I have seen this was not working in some older Excel versions.

**Comment by Silex64** [comment]
Thank you for your feedback. I use Microsoft Excel 2019 MSO (16.0.10361.20002) 32-bit

**Comment by pyscripter** [comment]
I am not sure what is the problem.  It works in some Excel versions and doesn't on others.  If you are familiar with VBA and you can debug the problem I would be most grateful.

**Comment by Silex64** [comment]
Thank you. I will let you know if I find a solution. I also have the issue that, following your correlation table example and linking this table to the formulas in the variables, I get the following error message: "The risk input functions have not been properly linked to the correlation matrix at Sheet1!$K$13:$M$15

**Comment by mrjkwon** [comment]
Have you changed the name of the worksheet containing the Tornado chart, by chance? I'm facing a similar issue, and am landing on the use of the Indirect formula when defining the TornadoX and TornadoY named ranges.

**Comment by pyscripter** [comment]
Please try the latest version of the addin and report back regarding this issue.
